# Change these first
owner: clarkwrks # Your GitHub organization or username, where this repository lives
repo: resnet-status # The name of this repository

sites:
  - name: Main
    url: https://www.nsercresnet.ca
  - name: Data Portal
    url: https://data.nsercresnet.ca
  - name: Document Library
    url: https://docs.nsercresnet.ca
  - name: Applications
    url: https://apps.nsercresnet.ca/
  - name: Monteregie Storymap
    url: https://apps.nsercresnet.ca/story/monteregie/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.clarkwrks.com
  # baseUrl: /resnet-status
  logoUrl: https://www.nsercresnet.ca/uploads/6/3/9/8/6398839/published/resnet-logo-4x.png
  name: ResNet Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: ResNet Status
      href: /
    - title: Cloud Server Status
      href: https://status.alliancecan.ca/
   # - title: GitHub
   #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
